INSERT INTO Estado(Cd_Estado,Sg_Estado, Nm_estado) VALUES (01,'AC', 'Acre');
INSERT INTO estado (Cd_Estado,  Sg_Estado, Nm_Estado) VALUES (02,  'AL', 'Alagoas');
INSERT INTO estado (Cd_Estado,  Sg_Estado, Nm_Estado) VALUES (03,  'AP', 'Amapá');
INSERT INTO estado (Cd_Estado,  Sg_Estado, Nm_Estado) VALUES (04,  'AM', 'Amazonas');
INSERT INTO estado (Cd_Estado,  Sg_Estado, Nm_Estado) VALUES (05,  'BA', 'Bahia');
INSERT INTO estado (Cd_Estado,  Sg_Estado, Nm_Estado) VALUES (06,  'CE', 'Ceará');
INSERT INTO estado (Cd_Estado,  Sg_Estado, Nm_Estado) VALUES (07,  'DF', 'Distrito Federal');
INSERT INTO estado (Cd_Estado,  Sg_Estado, Nm_Estado) VALUES (08,  'ES', 'Espírito Santo');
INSERT INTO estado (Cd_Estado,  Sg_Estado, Nm_Estado) VALUES (09,  'GO', 'Goiás');
INSERT INTO estado (Cd_Estado,  Sg_Estado, Nm_Estado) VALUES (10,  'MA', 'Maranhão');
INSERT INTO estado (Cd_Estado,  Sg_Estado, Nm_Estado) VALUES (11,  'MT', 'Mato Grosso');
INSERT INTO estado (Cd_Estado,  Sg_Estado, Nm_Estado) VALUES (12,  'MS', 'Mato Grosso do Sul');
INSERT INTO estado (Cd_Estado,  Sg_Estado, Nm_Estado) VALUES (13,  'MG', 'Minas Gerais');
INSERT INTO estado (Cd_Estado,  Sg_Estado, Nm_Estado) VALUES (14,  'PA', 'Pará');
INSERT INTO estado (Cd_Estado,  Sg_Estado, Nm_Estado) VALUES (15,  'PB', 'Paraíba');
INSERT INTO estado (Cd_Estado,  Sg_Estado, Nm_Estado) VALUES (16,  'PR', 'Paraná');
INSERT INTO estado (Cd_Estado,  Sg_Estado, Nm_Estado) VALUES (17,  'PE', 'Pernambuco');
INSERT INTO estado (Cd_Estado,  Sg_Estado, Nm_Estado) VALUES (18,  'PI', 'Piauí');
INSERT INTO estado (Cd_Estado,  Sg_Estado, Nm_Estado) VALUES (19,  'RJ', 'Rio de Janeiro');
INSERT INTO estado (Cd_Estado,  Sg_Estado, Nm_Estado) VALUES (20,  'RN', 'Rio Grande do Norte');
INSERT INTO estado (Cd_Estado,  Sg_Estado, Nm_Estado) VALUES (21,  'RS', 'Rio Grande do Sul');
INSERT INTO estado (Cd_Estado,  Sg_Estado, Nm_Estado) VALUES (22,  'RO', 'Rondônia');
INSERT INTO estado (Cd_Estado,  Sg_Estado, Nm_Estado) VALUES (23,  'RR', 'Roraima');
INSERT INTO estado (Cd_Estado,  Sg_Estado, Nm_Estado) VALUES (24,  'SC', 'Santa Catarina');
INSERT INTO estado (Cd_Estado,  Sg_Estado, Nm_Estado) VALUES (25,  'SP', 'São Paulo');
INSERT INTO estado (Cd_Estado,  Sg_Estado, Nm_Estado) VALUES (26,  'SE', 'Sergipe');
INSERT INTO estado (Cd_Estado,  Sg_Estado, Nm_Estado) VALUES (27,  'TO', 'Tocantins');