//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4234
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrcamentoNet.View {
    
    
    public partial class Guia {
        
        /// <summary>
        /// uxTituloH1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl uxTituloH1;
        
        /// <summary>
        /// MensagemSuperiorControle1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OrcamentoNet.View.controles.MensagemSuperiorControle MensagemSuperiorControle1;
        
        /// <summary>
        /// uxrptCategorias control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DataList uxrptCategorias;
        
        /// <summary>
        /// FornecedoresControle1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OrcamentoNet.View.controles.FornecedoresControle FornecedoresControle1;
        
        /// <summary>
        /// DepoimentoOrcamentoOnline1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OrcamentoNet.View.DepoimentoOrcamentoOnline DepoimentoOrcamentoOnline1;
    }
}
